FROM golang:1.20 AS builder

WORKDIR /app

COPY backend/go.mod backend/go.sum ./
RUN go mod download

COPY backend/ ./
RUN go build -o todo-app ./cmd/main.go

FROM gcr.io/distroless/base

WORKDIR /root/

COPY --from=builder /app/todo-app .

CMD ["./todo-app"]